spring.application.name=LLM_wiki
# Python AI ?????
app.ai-engine.url=http://localhost:8000/api/ai/process
# Python ???????
app.ai-engine.chat-url=http://localhost:8000/api/ai/chat
# ?? Wiki ?????
app.ai-engine.save-wiki-url=http://localhost:8000/api/ai/save_to_wiki

app.ai-engine.wiki-list-url=http://localhost:8000/api/ai/wiki/list
app.ai-engine.wiki-content-url=http://localhost:8000/api/ai/wiki/content

server.port=8080
# ????????????? Obsidian ???
app.obsidian.vault-path=E:\LLM_wiki
# ?? Qwen API Key ???????
app.llm.api-key=sk-21b28f745dee492ab5c8a4de46d9413b
# ????????? (???? 20MB)
spring.servlet.multipart.max-file-size=20MB
# ????????? (???? 20MB)
spring.servlet.multipart.max-request-size=20MB